apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/stolostron/volsync-operator-product-fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    # when adding filter for directory use "directory/***".pathChanged()
    # when adding filter for git submodule use "submodule".pathChanged()
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      (".tekton/volsync-fbc-4-14-pull-request.yaml".pathChanged() ||
      ".tekton/volsync-fbc-4-14-push.yaml".pathChanged() ||
      "catalog.Dockerfile".pathChanged() ||
      "catalog-4-14/***".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: volsync-fbc-4-14
    appstudio.openshift.io/component: volsync-fbc-4-14
    pipelines.appstudio.openshift.io/type: build
  name: volsync-fbc-4-14-on-push
  namespace: volsync-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/volsync-tenant/volsync-fbc-4-14:{{revision}}
    - name: build-platforms
      value:
        - linux/x86_64
        - linux/ppc64le
        - linux/s390x
        - linux/arm64
    - name: dockerfile
      value: catalog.Dockerfile
    - name: hermetic
      value: "true"
    - name: build-args
      value:
        - OPM_IMAGE=registry.redhat.io/openshift4/ose-operator-registry:v4.14
        - INPUT_DIR=catalog-4-14
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/stolostron/konflux-build-catalog.git
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common-fbc.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-volsync-fbc-4-14
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
